### PR TITLE
Add consumergroup member count metric

### PR DESCRIPTION
**Pull request by godwhoa**
Accidentally sorted the imports, hopefully that won't be an issue.

Closes: #18

### CODE REVIEW

**Comment by weeco** [comment]
Hey,
thanks for the PR. Currently I am short on time, so it may take a while until I reviewed and tested the proposed changes.

**Comment by godwhoa** [comment]
Sure take your time :+1:

**Comment by weeco** [comment]
Change LGTM, but the `processGroupMetadata` method does not handle tombstones yet. Accordingly you'll always store the groupMetadata as we receive it, but we never delete it. 

This requires further attention and I am not entirely sure how tombstones are supposed to be handled there without investigating that on my own.

**Comment by godwhoa** [comment]
I don't fully understand tombstones thing yet, but I vaguely understood it looking at `processOffsetCommit`'s handling of tombstones. 
If it can be done in the same way for `processGroupMetadata` as well I can implement it.
If not, I can wait for someone more knowledgeable to implement tombstone handling in `processGroupMetadata` before this gets merged.

**Comment by tkdrahn** [comment]
subscribed - would like this metric as well

**Comment by tkdrahn** [comment]
are there any plans to merge this PR?

**Comment by weeco** [comment]
This PR is incomplete because it doesn't handle tombstones and therefore introduces a potential memory leak. In general I'd like to add that I intend to rewrite Kafka Minion in .NET Core and I will potentially to add features like this during the rewrite.

Thus I believe it's appropriate to close the PR, thank you for the contribution and effort though!

**Pull request closed without merging**
